services:
  web-proxy:
    image: 'jc21/nginx-proxy-manager:2'
    restart: always
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - web-proxy-data:/data
      - letsencrypt-data:/etc/letsencrypt
  icecast-proxy:
    image: 'jc21/nginx-proxy-manager:2'
    restart: always
    ports:
      - '82:81'
      - '8000:443'
    volumes:
      - icecast-proxy-data:/data
      - letsencrypt-data:/etc/letsencrypt

volumes:
  web-proxy-data:
  icecast-proxy-data:
  letsencrypt-data: